-- =============================================================
-- Migration v4: 笔记模块
-- Run in Supabase SQL Editor AFTER migration-v3.sql
-- =============================================================

CREATE TABLE IF NOT EXISTS public.notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title text NOT NULL,
  note_date timestamptz NOT NULL,
  summary text,
  attachments jsonb NOT NULL DEFAULT '[]'::jsonb,
  uploader_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DROP TRIGGER IF EXISTS set_notes_updated_at ON public.notes;
CREATE TRIGGER set_notes_updated_at
  BEFORE UPDATE ON public.notes
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "authenticated users can read notes" ON public.notes;
CREATE POLICY "authenticated users can read notes"
  ON public.notes FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "users can insert own notes" ON public.notes;
CREATE POLICY "users can insert own notes"
  ON public.notes FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = uploader_id);

DROP POLICY IF EXISTS "uploaders or admins can update notes" ON public.notes;
CREATE POLICY "uploaders or admins can update notes"
  ON public.notes FOR UPDATE TO authenticated
  USING (
    auth.uid() = uploader_id OR EXISTS (
      SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    auth.uid() = uploader_id OR EXISTS (
      SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );

DROP POLICY IF EXISTS "uploaders or admins can delete notes" ON public.notes;
CREATE POLICY "uploaders or admins can delete notes"
  ON public.notes FOR DELETE TO authenticated
  USING (
    auth.uid() = uploader_id OR EXISTS (
      SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );
