-- =============================================================
-- Migration v2: 周任务制 / 收藏 / 请假 / 通知 / 精选评论
-- Run this on your Supabase project SQL editor
-- =============================================================

-- 1. 精选评论标记
ALTER TABLE public.comments
  ADD COLUMN IF NOT EXISTS is_featured boolean NOT NULL DEFAULT false;

-- 2. 请假申请表
CREATE TABLE IF NOT EXISTS public.leave_requests (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  week_start  date NOT NULL,           -- Thursday of the week being requested
  reason      text NOT NULL,
  status      text NOT NULL DEFAULT 'pending'
                CHECK (status IN ('pending', 'approved', 'rejected')),
  admin_id    uuid REFERENCES public.profiles(id),
  admin_note  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS leave_requests_user_week_uidx
  ON public.leave_requests (user_id, week_start);

DROP TRIGGER IF EXISTS set_leave_requests_updated_at ON public.leave_requests;
CREATE TRIGGER set_leave_requests_updated_at
  BEFORE UPDATE ON public.leave_requests
  FOR EACH ROW EXECUTE PROCEDURE public.set_updated_at();

-- 3. 通知表
CREATE TABLE IF NOT EXISTS public.notifications (
  id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title     text NOT NULL,
  content   text NOT NULL,
  is_read   boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. 文献收藏表
CREATE TABLE IF NOT EXISTS public.paper_bookmarks (
  paper_id   bigint NOT NULL REFERENCES public.papers(id) ON DELETE CASCADE,
  user_id    uuid   NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (paper_id, user_id)
);

-- 5. 评论收藏表
CREATE TABLE IF NOT EXISTS public.comment_bookmarks (
  comment_id bigint NOT NULL REFERENCES public.comments(id) ON DELETE CASCADE,
  user_id    uuid   NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (comment_id, user_id)
);

-- =============================================================
-- RLS 策略
-- =============================================================

-- leave_requests
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users can read own leave requests" ON public.leave_requests;
CREATE POLICY "users can read own leave requests"
  ON public.leave_requests FOR SELECT TO authenticated
  USING (auth.uid() = user_id OR EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
  ));

DROP POLICY IF EXISTS "users can insert own leave request" ON public.leave_requests;
CREATE POLICY "users can insert own leave request"
  ON public.leave_requests FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "admins can update leave requests" ON public.leave_requests;
CREATE POLICY "admins can update leave requests"
  ON public.leave_requests FOR UPDATE TO authenticated
  USING (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
  ));

DROP POLICY IF EXISTS "users can delete own pending leave" ON public.leave_requests;
CREATE POLICY "users can delete own pending leave"
  ON public.leave_requests FOR DELETE TO authenticated
  USING (auth.uid() = user_id AND status = 'pending');

-- notifications
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users can read own notifications" ON public.notifications;
CREATE POLICY "users can read own notifications"
  ON public.notifications FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "admins can insert notifications" ON public.notifications;
CREATE POLICY "admins can insert notifications"
  ON public.notifications FOR INSERT TO authenticated
  WITH CHECK (EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
  ));

DROP POLICY IF EXISTS "users can update own notifications" ON public.notifications;
CREATE POLICY "users can update own notifications"
  ON public.notifications FOR UPDATE TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- paper_bookmarks
ALTER TABLE public.paper_bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users can read own paper bookmarks" ON public.paper_bookmarks;
CREATE POLICY "users can read own paper bookmarks"
  ON public.paper_bookmarks FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "users can insert paper bookmarks" ON public.paper_bookmarks;
CREATE POLICY "users can insert paper bookmarks"
  ON public.paper_bookmarks FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "users can delete own paper bookmarks" ON public.paper_bookmarks;
CREATE POLICY "users can delete own paper bookmarks"
  ON public.paper_bookmarks FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- comment_bookmarks
ALTER TABLE public.comment_bookmarks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users can read own comment bookmarks" ON public.comment_bookmarks;
CREATE POLICY "users can read own comment bookmarks"
  ON public.comment_bookmarks FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "users can insert comment bookmarks" ON public.comment_bookmarks;
CREATE POLICY "users can insert comment bookmarks"
  ON public.comment_bookmarks FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "users can delete own comment bookmarks" ON public.comment_bookmarks;
CREATE POLICY "users can delete own comment bookmarks"
  ON public.comment_bookmarks FOR DELETE TO authenticated
  USING (auth.uid() = user_id);

-- admins can mark comments as featured
DROP POLICY IF EXISTS "admins can update comment featured" ON public.comments;
CREATE POLICY "admins can update comment featured"
  ON public.comments FOR UPDATE TO authenticated
  USING (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  )
  WITH CHECK (
    auth.uid() = user_id OR EXISTS (
      SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role = 'admin'
    )
  );
