create extension if not exists moddatetime schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null unique,
  username text not null unique,
  real_name text not null,
  student_id text,
  research_direction text,
  avatar_url text,
  role text not null default 'member' check (role in ('admin', 'member')),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.papers (
  id bigint generated by default as identity primary key,
  title text not null,
  authors text not null,
  abstract text,
  file_path text not null,
  file_size bigint,
  original_filename text,
  uploader_id uuid not null references public.profiles(id) on delete cascade,
  presentation_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  paper_id bigint not null references public.papers(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  parent_id bigint references public.comments(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.comment_likes (
  comment_id bigint not null references public.comments(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (comment_id, user_id)
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (
    id,
    email,
    username,
    real_name,
    student_id,
    research_direction
  )
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'real_name', split_part(new.email, '@', 1)),
    nullif(new.raw_user_meta_data ->> 'student_id', ''),
    nullif(new.raw_user_meta_data ->> 'research_direction', '')
  )
  on conflict (id) do update
  set
    email = excluded.email,
    username = excluded.username,
    real_name = excluded.real_name,
    student_id = excluded.student_id,
    research_direction = excluded.research_direction;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_papers_updated_at on public.papers;
create trigger set_papers_updated_at before update on public.papers
for each row execute procedure public.set_updated_at();

drop trigger if exists set_comments_updated_at on public.comments;
create trigger set_comments_updated_at before update on public.comments
for each row execute procedure public.set_updated_at();

alter table public.profiles enable row level security;
alter table public.papers enable row level security;
alter table public.comments enable row level security;
alter table public.comment_likes enable row level security;

drop policy if exists "authenticated users can read profiles" on public.profiles;
create policy "authenticated users can read profiles"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "users can update own profile" on public.profiles;
create policy "users can update own profile"
on public.profiles for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "admins can update profiles" on public.profiles;
create policy "admins can update profiles"
on public.profiles for update
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "users can insert own profile" on public.profiles;
create policy "users can insert own profile"
on public.profiles for insert
to authenticated
with check (auth.uid() = id);

drop policy if exists "authenticated users can read papers" on public.papers;
create policy "authenticated users can read papers"
on public.papers for select
to authenticated
using (true);

drop policy if exists "authenticated users can create papers" on public.papers;
create policy "authenticated users can create papers"
on public.papers for insert
to authenticated
with check (auth.uid() = uploader_id);

drop policy if exists "uploaders or admins can update papers" on public.papers;
create policy "uploaders or admins can update papers"
on public.papers for update
to authenticated
using (
  auth.uid() = uploader_id or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  auth.uid() = uploader_id or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "uploaders or admins can delete papers" on public.papers;
create policy "uploaders or admins can delete papers"
on public.papers for delete
to authenticated
using (
  auth.uid() = uploader_id or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "authenticated users can read comments" on public.comments;
create policy "authenticated users can read comments"
on public.comments for select
to authenticated
using (true);

drop policy if exists "authenticated users can create comments" on public.comments;
create policy "authenticated users can create comments"
on public.comments for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "authors or admins can update comments" on public.comments;
create policy "authors or admins can update comments"
on public.comments for update
to authenticated
using (
  auth.uid() = user_id or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
)
with check (
  auth.uid() = user_id or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "authors or admins can delete comments" on public.comments;
create policy "authors or admins can delete comments"
on public.comments for delete
to authenticated
using (
  auth.uid() = user_id or exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and p.role = 'admin'
  )
);

drop policy if exists "authenticated users can read likes" on public.comment_likes;
create policy "authenticated users can read likes"
on public.comment_likes for select
to authenticated
using (true);

drop policy if exists "authenticated users can like comments" on public.comment_likes;
create policy "authenticated users can like comments"
on public.comment_likes for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "users can unlike own likes" on public.comment_likes;
create policy "users can unlike own likes"
on public.comment_likes for delete
to authenticated
using (auth.uid() = user_id);
